const escapeHtml = (value) => String(value)
  .replace(/&/g, '&amp;')
  .replace(/</g, '&lt;')
  .replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;')
  .replace(/'/g, '&#039;');

const htmlPages = (req, res) => {
  const pagePath = req.path === '/' ? '/pages' : `/pages${req.path}`;
  const links = [
    ['/pages', 'Pages home'],
    ['/pages/health', 'Health page'],
    ['/pages/dashboard', 'Dashboard page'],
    ['/pages/users', 'Users page'],
    ['/pages/workspaces', 'Workspaces page'],
    ['/pages/projects', 'Projects page'],
    ['/pages/tasks', 'Tasks and filters page'],
    ['/pages/submissions', 'Submissions page'],
    ['/pages/meetings', 'Meetings page'],
    ['/pages/messages', 'Messages page'],
    ['/pages/notifications', 'Notifications page'],
  ];

  res.status(200).send(`
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Collaborative Workspace Server Pages</title>
        <style>
          body { margin: 0; padding: 32px; font-family: Arial, sans-serif; color: #0f172a; background: #f3f6fb; }
          main { max-width: 860px; margin: auto; padding: 28px; background: white; border: 1px solid #dfe7f2; border-radius: 14px; }
          h1 { margin-top: 0; }
          code { background: #eef2ff; padding: 3px 6px; border-radius: 5px; }
          ul { padding-left: 20px; line-height: 1.9; }
          a { color: #2563eb; }
          .request { padding: 14px; background: #09111f; color: #dbeafe; border-radius: 8px; }
        </style>
      </head>
      <body>
        <main>
          <h1>Collaborative Workspace</h1>
          <p>This HTML response was generated by Express middleware.</p>
          <div class="request">
            <strong>Request:</strong>
            ${escapeHtml(req.method)} ${escapeHtml(req.originalUrl)}
          </div>
          <h2>Server-rendered pages</h2>
          <ul>
            ${links.map(([url, label]) => `<li><a href="${url}">${label}</a></li>`).join('')}
          </ul>
          <p>The <code>/api/*</code> endpoints remain JSON endpoints for the frontend and API clients.</p>
          <p>Current page: <code>${escapeHtml(pagePath)}</code></p>
        </main>
      </body>
    </html>
  `);
};

module.exports = htmlPages;
